spring.application.name=SkillExchangePlatform
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

# Optional H2 console for local debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret Key
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Port number
server.port=8000